import type { Metadata } from "next";
import Link from "next/link";

// Terms of service for the hosted (cloud) product. Plain and honest, same
// register as /privacy. Linked from checkout, the billing page, and the
// footer. Self-hosters run their own instance under AGPL and aren't bound by
// these commercial terms - only the dispatchseo.com service is.

export const metadata: Metadata = {
  title: "Terms of service - DispatchSEO",
  description: "The terms for using the hosted DispatchSEO service at dispatchseo.com.",
};

const EFFECTIVE = "July 22, 2026";
const CONTACT = "support@dispatchseo.com";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl space-y-8 px-6 py-16 text-neutral-300">
      <div className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight text-white">Terms of service</h1>
        <p className="text-sm text-neutral-500">Effective {EFFECTIVE}</p>
      </div>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">What these terms cover</h2>
        <p>
          These terms govern the hosted DispatchSEO service at dispatchseo.com, operated by the
          DispatchSEO maintainer (&quot;we&quot;, &quot;us&quot;). DispatchSEO is also open
          source; if you self-host it, these commercial terms do not apply to you - only the
          software&apos;s license does. By creating an account or subscribing to the hosted
          service, you agree to these terms.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">The service</h2>
        <p>
          DispatchSEO researches keywords for your website, drafts articles and tools as pull
          requests to your repository, and tracks your search rankings. You connect your own
          GitHub repository, Google Search Console account, and Claude (Claude Code)
          subscription; content is generated by your Claude subscription, not by us. We provide
          the research data, scheduling, dashboard, and rank tracking. You are responsible for
          reviewing and approving anything published to your site.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">Plans, billing, and cancellation</h2>
        <p>
          Paid plans are billed monthly in advance through our payment provider, Polar, who acts
          as the merchant of record. Each plan sets limits (number of sites and tracked
          keywords); those limits are enforced on your account. You can change or cancel your
          plan at any time from the billing portal; cancellation takes effect at the end of the
          current billing period, and you keep access until then.
        </p>
        <p>
          <strong className="text-neutral-100">Money-back guarantee.</strong> If DispatchSEO
          hasn&apos;t measurably helped your site within 90 days, contact us at {CONTACT} and
          we&apos;ll refund your subscription payments for that period.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">Acceptable use</h2>
        <p>
          Use the service for your own websites and content. Don&apos;t use it to generate
          spam, to publish content that infringes others&apos; rights, or in a way that abuses
          the connected APIs (Google Search Console, GitHub, DataForSEO) or violates their
          terms. We may suspend accounts that do.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">Your data and content</h2>
        <p>
          You own your site, your content, and the pull requests generated for you. How we
          handle the data you connect (including Google Search Console data) is described in our{" "}
          <Link className="text-white underline" href="/privacy">
            privacy policy
          </Link>
          . You can disconnect an integration or delete your account at any time.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">Warranty and liability</h2>
        <p>
          The service is provided &quot;as is&quot;. SEO results depend on many factors outside
          our control, and we don&apos;t guarantee particular rankings or traffic. To the extent
          allowed by law, our liability for any claim relating to the service is limited to the
          amount you paid us in the three months before the claim.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-medium text-white">Changes and contact</h2>
        <p>
          We may update these terms; material changes are posted here with a new effective date.
          Questions about these terms: {CONTACT}.
        </p>
      </section>

      <p className="text-sm text-neutral-500">
        <Link className="underline" href="/">
          Back to dispatchseo.com
        </Link>
      </p>
    </main>
  );
}
