-- GENERATED by scripts/generate-setup-sql.mjs - do not edit by hand.
-- Every numbered migration, concatenated in order. Idempotent: safe to
-- run on a fresh database AND on one that already has some migrations
-- applied (each statement is IF NOT EXISTS / additive).

-- ============ 0001_init.sql ============
-- SEO Manager MVP - initial schema.
-- Single user. Access is server-side only via the service role key.
-- RLS is ENABLED with zero policies on every table: that makes the anon and
-- authenticated PostgREST roles see nothing, while the service role bypasses
-- RLS entirely. This is the "no RLS complexity" posture without leaving the
-- tables open to anyone holding the public anon key.

-- pages first: keywords.target_page_id references it.
create table if not exists pages (
  id uuid primary key default gen_random_uuid(),
  url text not null unique,
  title text,
  type text,                          -- guide | tool | landing
  primary_keyword text,
  published_at timestamptz,
  pr_url text,
  created_at timestamptz default now()
);

-- tracked keywords
create table if not exists keywords (
  id uuid primary key default gen_random_uuid(),
  keyword text not null unique,
  search_volume int,
  keyword_difficulty numeric,
  cpc numeric,
  intent text,                        -- informational/commercial/etc
  status text default 'tracking',     -- tracking | paused
  target_page_id uuid references pages(id),
  created_at timestamptz default now()
);

-- rank history (one row per keyword per check)
create table if not exists rank_checks (
  id uuid primary key default gen_random_uuid(),
  keyword_id uuid references keywords(id) on delete cascade,
  position int,                       -- null = not in top 100
  url text,                           -- which page ranks
  checked_at timestamptz default now()
);

-- the daily cron reads/writes per keyword ordered by time
create index if not exists rank_checks_keyword_checked_idx
  on rank_checks (keyword_id, checked_at desc);

-- the suggestions queue (heart of the system)
create table if not exists suggestions (
  id uuid primary key default gen_random_uuid(),
  type text not null,                 -- guide | tool | backlink | update
  title text not null,
  primary_keyword text,
  keyword_volume int,
  keyword_difficulty numeric,
  rationale text,                     -- why this is worth doing
  spec jsonb,                         -- brief: outline, angle, tool functionality, target url for backlinks
  status text default 'pending',      -- pending | approved | rejected | in_progress | done
  result_pr_url text,
  created_at timestamptz default now(),
  decided_at timestamptz,
  completed_at timestamptz
);

-- daily GSC snapshot
create table if not exists gsc_stats (
  id uuid primary key default gen_random_uuid(),
  date date not null unique,
  clicks int,
  impressions int,
  ctr numeric,
  avg_position numeric,
  top_queries jsonb,                  -- [{query, clicks, impressions, position}] top 20
  top_pages jsonb
);

-- backlink prospects
create table if not exists backlink_prospects (
  id uuid primary key default gen_random_uuid(),
  domain text not null,
  url text,
  domain_rating numeric,
  reason text,                        -- why relevant / where found
  status text default 'new',          -- new | contacted | acquired | rejected
  created_at timestamptz default now()
);

alter table pages enable row level security;
alter table keywords enable row level security;
alter table rank_checks enable row level security;
alter table suggestions enable row level security;
alter table gsc_stats enable row level security;
alter table backlink_prospects enable row level security;

-- ============ 0002_playbook_status.sql ============
-- Playbook progress: which foundational-backlink items the user has completed.
-- One row per playbook item slug (the curated registry lives in code at
-- src/lib/playbook-data.ts - only the per-user progress is stored here).
-- Same RLS posture as 0001: enabled with no policies, so only the service-role
-- client (src/lib/db.ts) can read/write.

create table if not exists playbook_status (
  slug text primary key,
  status text not null default 'todo' check (status in ('todo', 'done', 'skipped')),
  done_at timestamptz
);

alter table playbook_status enable row level security;

-- ============ 0003_site_profile.sql ============
-- Site profile: the product identity the backlink playbook personalizes from
-- (name, tagline, descriptions at directory-friendly lengths, categories,
-- tags). Written by the /seo-setup agent command via the set_site_profile MCP
-- tool; read by the dashboard to prefill every playbook submission and
-- @browser command.
--
-- Single-tenant: one row, id locked to 1. The future multi-tenant version
-- replaces this with per-tenant rows keyed to an account.
-- Same RLS posture as 0001/0002: enabled, no policies, service-role only.

create table if not exists site_profile (
  id int primary key default 1 check (id = 1),
  name text not null,
  url text not null,
  tagline text not null,          -- <= 60 chars, fits most directory tagline limits
  short_description text not null, -- <= 160 chars, meta-description-sized fields
  long_description text not null,  -- 300-600 chars, roomy description fields
  categories text[] not null default '{}',
  tags text[] not null default '{}',
  updated_at timestamptz not null default now()
);

alter table site_profile enable row level security;

-- No seed. The dashboard shows its "set up your site profile" card (and the
-- agent's /seo-setup writes the row) once the owner's real site exists - a
-- fresh instance must never be born describing someone else's product.
-- (Until 2026-07-21 this seeded ClockedCode, this repo's original tenant;
-- existing installs keep whatever row they already have.)

-- ============ 0004_projects.sql ============
-- 0004: projects - the tenant axis. One deployment now manages many sites:
-- every operational table gains a project_id, and the dashboard grows a
-- Vercel-style project switcher.
--
-- Zero-downtime plan: project_id gets a DEFAULT of the ClockedCode project's
-- FIXED id, so code deployed before this migration keeps writing valid rows
-- during the migration->deploy window, and old rows backfill automatically
-- (ADD COLUMN ... DEFAULT fills existing rows).

create extension if not exists pgcrypto;

create table if not exists projects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  domain text not null unique,              -- bare domain: clockedcode.com
  gsc_site_url text,                        -- GSC property (sc-domain:... or https://...); null until connected
  github_repo text,                         -- owner/repo the content PRs land in; null = no pipeline yet
  mcp_token text not null unique,           -- per-project bearer for the MCP server and CI workflows
  location_code int not null default 2840,  -- DataForSEO market (2840 = US)
  language_code text not null default 'en',
  mode text not null default 'semi' check (mode in ('semi', 'auto')),
  created_at timestamptz not null default now()
);
-- Same posture as every other table here: RLS on, zero policies - only the
-- service-role key (the dashboard + MCP server) can read or write.
alter table projects enable row level security;

-- Project #1, with a FIXED id so it can be the column default below. Seeded
-- NEUTRAL: the onboarding wizard claims this row in place for the owner's
-- first site (keeping the fixed id every project_id default points at), so
-- a fresh instance is never born configured for someone else's product.
-- The legacy MCP_API_KEY env var maps to this row by its fixed id, whatever
-- slug/name the wizard later gives it. Conflict target is the id: existing
-- installs (whose row may be renamed, or the pre-2026-07-21 ClockedCode
-- seed) keep their row untouched.
insert into projects (id, slug, name, domain, gsc_site_url, github_repo, mcp_token, mode)
values (
  '00000000-0000-4000-8000-000000000001',
  'default',
  'Your site',
  '',
  null,
  null,
  encode(gen_random_bytes(24), 'hex'),
  'semi'
)
on conflict (id) do nothing;

-- ---- add project_id everywhere (default = ClockedCode) ---------------------

alter table pages              add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table keywords           add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table rank_checks        add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table suggestions        add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table gsc_stats          add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table backlink_prospects add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table playbook_status    add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);
alter table site_profile       add column if not exists project_id uuid not null default '00000000-0000-4000-8000-000000000001' references projects(id);

-- ---- retarget the uniqueness that assumed one site -------------------------

-- keyword text was globally unique; now unique per project.
alter table keywords drop constraint if exists keywords_keyword_key;
create unique index if not exists keywords_project_keyword_key on keywords (project_id, keyword);

-- page url was globally unique; now unique per project.
alter table pages drop constraint if exists pages_url_key;
create unique index if not exists pages_project_url_key on pages (project_id, url);

-- one GSC snapshot per day PER PROJECT.
alter table gsc_stats drop constraint if exists gsc_stats_date_key;
create unique index if not exists gsc_stats_project_date_key on gsc_stats (project_id, date);

-- playbook progress: one row per (project, item) instead of per item.
alter table playbook_status drop constraint if exists playbook_status_pkey;
alter table playbook_status add primary key (project_id, slug);

-- site_profile: one row per project instead of the single id=1 row. The id
-- column stays as pk but gets a sequence so new projects can insert rows.
alter table site_profile drop constraint if exists site_profile_id_check;
create sequence if not exists site_profile_id_seq owned by site_profile.id;
select setval('site_profile_id_seq', greatest((select coalesce(max(id), 1) from site_profile), 1));
alter table site_profile alter column id set default nextval('site_profile_id_seq');
create unique index if not exists site_profile_project_key on site_profile (project_id);

-- ---- filter indexes for the per-project queries ----------------------------

create index if not exists suggestions_project_idx        on suggestions (project_id, created_at);
create index if not exists rank_checks_project_idx        on rank_checks (project_id, checked_at desc);
create index if not exists backlink_prospects_project_idx on backlink_prospects (project_id, created_at desc);

-- ============ 0005_index_requested.sql ============
-- "Request Google indexing" follow-up state for published pages.
--
-- Google has no API for pushing regular pages into its index (IndexNow is
-- Bing/Yandex only; Google's Indexing API is restricted to job postings and
-- livestreams; the URL Inspection API is read-only). The fastest legitimate
-- path is a human clicking "Request indexing" in Search Console, so the
-- dashboard surfaces a next-action card for every freshly published page.
-- Marking the card done stamps this column and hides it.
alter table pages add column if not exists index_requested_at timestamptz;

comment on column pages.index_requested_at is
  'When the user marked the manual GSC "Request indexing" step done for this page. Null = still waiting (card shows on Home while the page is fresh).';

-- ============ 0006_cascade_deletes.sql ============
-- 0006: deletable projects. Deleting a projects row now cascades through every
-- table that carries its project_id, so "Delete project" is one statement and
-- can never leave orphans behind.

alter table pages
  drop constraint if exists pages_project_id_fkey,
  add constraint pages_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table keywords
  drop constraint if exists keywords_project_id_fkey,
  add constraint keywords_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table rank_checks
  drop constraint if exists rank_checks_project_id_fkey,
  add constraint rank_checks_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table suggestions
  drop constraint if exists suggestions_project_id_fkey,
  add constraint suggestions_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table gsc_stats
  drop constraint if exists gsc_stats_project_id_fkey,
  add constraint gsc_stats_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table backlink_prospects
  drop constraint if exists backlink_prospects_project_id_fkey,
  add constraint backlink_prospects_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table playbook_status
  drop constraint if exists playbook_status_project_id_fkey,
  add constraint playbook_status_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

alter table site_profile
  drop constraint if exists site_profile_project_id_fkey,
  add constraint site_profile_project_id_fkey
    foreign key (project_id) references projects(id) on delete cascade;

-- Rank history dies with its keyword (it is meaningless without it).
alter table rank_checks
  drop constraint if exists rank_checks_keyword_id_fkey,
  add constraint rank_checks_keyword_id_fkey
    foreign key (keyword_id) references keywords(id) on delete cascade;

-- A keyword survives its target page - it just loses the pointer.
alter table keywords
  drop constraint if exists keywords_target_page_id_fkey,
  add constraint keywords_target_page_id_fkey
    foreign key (target_page_id) references pages(id) on delete set null;

-- ============ 0007_dataforseo_per_project.sql ============
-- 0007: per-project DataForSEO credentials - the free-tier DIY model. Each
-- project brings its own DataForSEO account, so rank checks, keyword research,
-- and Domain Rating bill the project owner, never the platform. The default
-- (ClockedCode) project keeps using the env credentials; every other project
-- gets NO env fallback - without its own credentials the SERP and DR features
-- skip gracefully and the "Connect DataForSEO" setup card shows on Home.
--
-- Same storage posture as mcp_token: the table is reachable only through the
-- service-role key (RLS on, zero policies), never from a browser.

alter table projects add column if not exists dataforseo_login text;
alter table projects add column if not exists dataforseo_password text;

-- ============ 0008_domain_ratings.sql ============
-- 0008: domain_ratings - a persistent, per-project Domain Rating snapshot.
--
-- Why this exists: DR used to live only in unstable_cache. Any
-- revalidatePath('/', ...) (project connect/switch/delete/create, and every
-- '/'-scoped mutation) counts as "revalidate all data" in Next 16, so it wiped
-- BOTH the cached value AND the fetched_at timestamp the "updates in Xh Ym"
-- timer counts down from. The timer therefore snapped back to ~24h on every
-- dashboard mutation, and - worse - each wipe re-fired the paid DataForSEO
-- backlinks-summary call on the next render, defeating the 24h cache entirely.
--
-- Persisting the snapshot in the DB makes the 24h cache real: getDomainRating
-- reads this row, refreshes from DataForSEO only when fetched_at is older than
-- 24h, and the timer reflects the true last-fetch time. A page revalidation can
-- no longer reset it.
--
-- One row per project. Cascades on project delete, same as every other table
-- (see 0006). RLS on with zero policies - the service-role key (dashboard +
-- crons) is the only reader/writer, matching the house posture.

create table if not exists domain_ratings (
  project_id        uuid primary key references projects(id) on delete cascade,
  dr                int,          -- 0-100 (raw rank / 10, rounded); null = unknown
  rank              int,          -- raw 0-1000
  referring_domains int,
  backlinks         int,
  spam_score        int,          -- 0-100
  fetched_at        timestamptz not null default now()
);

alter table domain_ratings enable row level security;

-- ============ 0009_keyword_source.sql ============
-- 0009: per-project keyword data source - the onboarding wizard's choice.
-- Three modes the engine supports end to end:
--   'dataforseo'  paid, most accurate (the pre-wizard default, so existing
--                 projects keep behaving exactly as before)
--   'serpapi'     free mode with a bring-your-own SerpApi key (250 searches/mo
--                 free tier) - live SERP checks on a weekly cadence
--   'gsc'         pure free mode - positions come from Search Console only
-- serpapi_key is stored encrypted at rest (same crypto.ts posture as the
-- DataForSEO password). powerups_skipped remembers which optional setup cards
-- the user unchecked in the wizard so Home stops showing them.

alter table projects add column if not exists keyword_source text not null default 'dataforseo'
  check (keyword_source in ('dataforseo', 'serpapi', 'gsc'));
alter table projects add column if not exists serpapi_key text;
alter table projects add column if not exists powerups_skipped text[] not null default '{}';

-- ============ 0010_indexed_verification.sql ============
-- Verified Google index state for published pages.
--
-- index_requested_at (0005) records that the manual "Request indexing" step
-- happened; these two columns record what Google actually says. The URL
-- Inspection API is read-only but that is exactly what verification needs:
-- the hourly-gsc cron asks it about every not-yet-confirmed page and stamps
-- indexed_at on a PASS verdict, so the dashboard's "Indexed" badge no longer
-- has to wait for the first impression to land. The agent's
-- mark_indexing_requested MCP tool also stamps indexed_at when Search Console
-- showed a page was already on Google.
alter table pages add column if not exists indexed_at timestamptz;
alter table pages add column if not exists index_checked_at timestamptz;

comment on column pages.indexed_at is
  'When Google was first confirmed to have this page indexed (URL Inspection API PASS, or the agent saw "URL is on Google" in Search Console). Null = not confirmed yet.';
comment on column pages.index_checked_at is
  'Last time the cron asked the URL Inspection API about this page - rotates the per-run inspection budget through the unconfirmed backlog.';

-- ============ 0011_automation_toggles.sql ============
-- 0011: per-automation toggles + the derived 'custom' publish mode.
--
-- The topbar mode is now derived from four automation flags:
--   semi   = auto_approve off, builds on, auto_merge off (you approve + merge)
--   auto   = everything on (fully hands-off)
--   custom = any other combination (set by toggling on the Automations page)
-- 'semi'/'auto' rows keep meaning the preset regardless of the flag columns;
-- the flag columns are only consulted when mode = 'custom'. Defaults are all
-- true so existing rows (both projects run auto today) keep their behavior.
--
-- Locked automations (weekly research, rank checks, GSC snapshots, tool
-- validation, IndexNow) have no columns on purpose - they cannot be disabled.

alter table projects drop constraint if exists projects_mode_check;
alter table projects
  add constraint projects_mode_check check (mode in ('semi', 'auto', 'custom'));

alter table projects
  add column if not exists auto_approve boolean not null default true,
  add column if not exists auto_build_guides boolean not null default true,
  add column if not exists auto_build_tools boolean not null default true,
  add column if not exists auto_merge boolean not null default true;

-- ============ 0012_conventions.sql ============
-- Conventions: the dashboard's mirror of each repo's .dispatchseo/conventions.md
-- - the site facts the setup workflow discovers (stack, build command, theme
-- tokens, voice rules, exemplars). Written by the agent via the set_conventions
-- MCP tool right after it writes the repo file; read by the dashboard's
-- Instructions page to show "here is how DispatchSEO adapted to YOUR site".
-- One upserted row per project (jsonb, a few KB) - current value only, the
-- repo file's git history is the archive.
-- Same RLS posture as every table: enabled, no policies, service-role only.

create table if not exists conventions (
  project_id uuid primary key default '00000000-0000-4000-8000-000000000001'
    references projects(id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table conventions enable row level security;

-- ============ 0013_trend_radar.sql ============
-- 0013: the trend radar - hype-window guide ideas with their own approval gate.
--
-- suggestions.source records which automation queued an idea: 'research' (the
-- weekly run - also the default, so every existing row keeps its meaning) or
-- 'trend-scan' (the Mon/Thu hype scan). Trend ideas get their own approval
-- flag because their value decays in days: with auto_trend on, the scan's
-- single best find approves itself and the daily builder ships it FIRST
-- (newest-first inside a 14-day freshness window - see the build-guide
-- instructions); off, trend ideas wait as pending like everything else.
-- Default true matches 0011's posture (existing projects run auto today).
--
-- projects.last_trend_scan_at lets the scheduled scan skip itself when a
-- manual Scan-now already ran within the last 48 hours; the scan stamps it
-- via the record_trend_scan MCP tool.

alter table suggestions
  add column if not exists source text not null default 'research';
alter table suggestions drop constraint if exists suggestions_source_check;
alter table suggestions
  add constraint suggestions_source_check check (source in ('research', 'trend-scan'));

alter table projects
  add column if not exists auto_trend boolean not null default true,
  add column if not exists last_trend_scan_at timestamptz;

-- ============ 0014_manual_queue.sql ============
-- 0014: manual ideas + a visible, owner-controlled build queue.
--
-- suggestions.source gains 'manual': ideas the owner typed themselves (via
-- the dashboard's Add-idea form or an explicit ask in Claude Code). Manual
-- ideas land already approved - the owner wrote them, there is nothing to
-- gate.
--
-- suggestions.queue_position makes the build order explicit and owner-owned.
-- Semantics (all consumers sort in JS so pre-migration deploys keep working):
--   - lowest position builds next; rows with NULL queue FIFO by created_at
--     AFTER every positioned row.
--   - a dashboard reorder rewrites the whole group (guides vs tools are
--     separate lists) to dense 1..n.
--   - "front" placement (trend approvals, manual do-this-next adds) writes
--     min(position) - 1, so it beats everything already positioned.

alter table suggestions
  add column if not exists queue_position int;

alter table suggestions drop constraint if exists suggestions_source_check;
alter table suggestions
  add constraint suggestions_source_check
  check (source in ('research', 'trend-scan', 'manual'));

-- ============ 0015_site_launched_at.sql ============
-- 0015: age-based publishing pace.
--
-- projects.site_launched_at is when the SITE went live - not when the project
-- was added to DispatchSEO. It drives the publishing-pace tiers (pacing.ts):
-- young sites publish slower, established sites ramp up to daily. Backfilled
-- from created_at (the best guess we have); the owner can correct it on the
-- Settings page.

alter table projects
  add column if not exists site_launched_at timestamptz not null default now();

update projects set site_launched_at = created_at;

-- ============ 0016_trend_topics.sql ============
-- 0016: the two-stage trend radar. Stage 1 (Scan now) sweeps the niche and
-- queues trending SUBJECTS as trend_topics rows - "codex vs claude code",
-- not finished guide ideas. Stage 2 fires when the owner picks a topic
-- (Get takes): a second workflow expands that one topic into 3-5 concrete
-- guide angles, which land as pending suggestions linked back to the topic
-- via suggestions.trend_topic_id. The owner then queues or builds the takes
-- they like. Splitting the pipeline this way also splits the cost: the sweep
-- is cheap, and deep validation only runs on subjects the owner chose.
--
-- projects.trend_scan_requested_at backs the Scan-now cooldown (30 min):
-- last_trend_scan_at stamps when a scan FINISHES (record_trend_scan), so a
-- separate request stamp is needed to block double-fires while one is still
-- running. trend_topics.expand_requested_at plays the same role per topic.

create table if not exists trend_topics (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null default '00000000-0000-4000-8000-000000000001'
    references projects(id) on delete cascade,
  title text not null,
  -- { why_now, signals[], sources[] } - the hype evidence from the sweep.
  evidence jsonb,
  -- new: waiting for the owner to pick or dismiss it
  -- expanding: Get takes fired, the expand workflow is running
  -- expanded: takes are on the radar as pending suggestions
  -- dismissed: the owner passed (or the scan aged it out after 14 days)
  status text not null default 'new'
    check (status in ('new', 'expanding', 'expanded', 'dismissed')),
  expand_requested_at timestamptz,
  expanded_at timestamptz,
  created_at timestamptz not null default now()
);

-- One radar row per subject per project - a re-scan that finds the same
-- subject again must not duplicate it (the scan dedupes by title too; this
-- is the backstop).
create unique index if not exists trend_topics_project_title
  on trend_topics (project_id, lower(title));

-- Same posture as every operational table: RLS on, zero policies - only the
-- service-role key can touch it.
alter table trend_topics enable row level security;

-- Takes remember which subject they came from, so the Trends page can group
-- them under their topic card. Pre-topic trend suggestions keep null and
-- render in their own legacy block.
alter table suggestions
  add column if not exists trend_topic_id uuid references trend_topics(id) on delete set null;

alter table projects
  add column if not exists trend_scan_requested_at timestamptz;

-- ============ 0017_content_surface.sql ============
-- 0017: the content-surface answer from onboarding. "Does the site have a
-- blog or content section?" - 'existing' = yes (content_path_hint optionally
-- says where), 'create' = no, scaffold one during setup, 'detect' = not sure,
-- the agent inspects the repo and decides. The setup workflow treats this as
-- a hint and reconciles it against what the repo actually contains - the
-- repo always wins, and a second content system is never created.
alter table projects
  add column if not exists content_mode text not null default 'detect'
    check (content_mode in ('existing', 'create', 'detect')),
  add column if not exists content_path_hint text;

-- ============ 0018_pipeline_installed.sql ============
-- 0018: explicit pipeline-install completion mark.
-- The install workflow's final step calls the mark_pipeline_installed MCP
-- tool, which stamps this; the Home setup card flips to its green
-- "installed" state on the stamp (with the conventions row kept as a
-- back-compat fallback signal). Additive and nullable - in-flight code that
-- never selects the column keeps working.
alter table projects add column if not exists pipeline_installed_at timestamptz;

-- ============ 0019_content_prefs.sql ============
-- 0019: owner content preferences - the Instructions page's template controls.
-- One JSONB blob per project ({} = untouched defaults): house_rules free text
-- injected into the build playbooks, disabled_archetypes removed from the
-- guide shape rotation, disabled_blocks dropped from the guide skeleton
-- (tldr / comparison_table / visuals / faq). Normalized and validated in
-- src/lib/content-prefs.ts - the column stays schemaless on purpose so new
-- knobs don't need a migration each.
alter table projects
  add column if not exists content_prefs jsonb not null default '{}'::jsonb;

-- ============ 0020_cron_runs.sql ============
-- 0020: cron run log - the "did my install break overnight?" answer.
-- Every cron route records one row per run (ok or failed, with the error
-- strings). The dashboard Home banner and the get_cron_health MCP tool read
-- the latest row per job; failure emails debounce against emailed_at.
-- No project_id on purpose: a run spans all projects (this is a system
-- table, not operational per-project state) - per-project error detail
-- lives inside the errors jsonb as "slug: message" strings.
create table if not exists cron_runs (
  id uuid primary key default gen_random_uuid(),
  job text not null,
  ok boolean not null,
  errors jsonb not null default '[]',
  emailed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists cron_runs_job_created_idx on cron_runs (job, created_at desc);

-- Same posture as every other table: RLS on, zero policies - only the
-- service-role key (server code) can touch it.
alter table cron_runs enable row level security;

-- ============ 0021_login_lockout.sql ============
-- 0021: login brute-force lockout (launch plan step 1, security).
-- One row per source IP. 5 failed password attempts inside 15 minutes lock
-- that IP out for 15 minutes. All mutation goes through the
-- record_login_failure() function so the count stays atomic without Redis -
-- the dashboard is single-user, this only has to beat scripted guessing.
-- Successful login deletes the row. Complements (not replaces) the Vercel
-- WAF rate-limit rule on the login POST.
create table if not exists login_attempts (
  ip text primary key,
  fails int not null default 1,
  first_fail_at timestamptz not null default now(),
  locked_until timestamptz
);

-- Same posture as every other table: RLS on, zero policies - service-role only.
alter table login_attempts enable row level security;

create or replace function record_login_failure(attempt_ip text)
returns timestamptz
language plpgsql
as $$
declare
  result timestamptz;
begin
  -- Expired lock or expired 15-minute window: start the count over.
  delete from login_attempts
    where ip = attempt_ip
      and ((locked_until is not null and locked_until < now())
        or (locked_until is null and first_fail_at < now() - interval '15 minutes'));

  insert into login_attempts (ip, fails, first_fail_at)
  values (attempt_ip, 1, now())
  on conflict (ip) do update set fails = login_attempts.fails + 1;

  update login_attempts
    set locked_until = now() + interval '15 minutes'
    where ip = attempt_ip and fails >= 5 and locked_until is null;

  select locked_until into result from login_attempts where ip = attempt_ip;
  return result;
end;
$$;

-- ============ 0022_waitlist.sql ============
-- Cloud waitlist signups from the public landing page (and the MCP parity
-- tool). Deliberately NOT project-scoped: an email on the waitlist belongs to
-- the cloud business, not to any tenant, so this table carries no project_id.
-- RLS on with zero policies, same as every other table - only the
-- service-role key touches it.

create table if not exists waitlist_signups (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  source text not null default 'landing',
  created_at timestamptz not null default now()
);

alter table waitlist_signups enable row level security;

-- ============ 0023_gsc_oauth.sql ============
-- 0023: per-project Google OAuth refresh token (launch plan step 3).
-- The dashboard's "Connect Google Search Console" button stores the OAuth
-- refresh token here (AES-256-GCM via crypto.ts, same posture as
-- serpapi_key / dataforseo_password). This is the seed of the cloud GSC
-- flow; the service-account path keeps working unchanged - OAuth is an
-- alternative connection, not a replacement. Additive and nullable.
alter table projects add column if not exists gsc_oauth_refresh_token text;

-- ============ 0024_waitlist_rate_limit.sql ============
-- 0024: waitlist per-IP rate limit (pre-launch security pass).
-- The landing waitlist form is the only unauthenticated write in the app; the
-- honeypot stops dumb bots but nothing stopped a scripted flood from filling
-- waitlist_signups and firing one Resend email per fresh address. Same shape
-- as 0021's login lockout: an atomic Postgres counter, 5 attempts per IP per
-- hour, code fails OPEN if this migration has not run yet.
create table if not exists waitlist_attempts (
  ip text primary key,
  attempts int not null default 1,
  window_start timestamptz not null default now()
);

-- Same posture as every other table: RLS on, zero policies - service-role only.
alter table waitlist_attempts enable row level security;

-- Returns true if this attempt is within the limit, false if the IP is over it.
create or replace function record_waitlist_attempt(attempt_ip text)
returns boolean
language plpgsql
as $$
declare
  current_attempts int;
begin
  delete from waitlist_attempts
    where ip = attempt_ip and window_start < now() - interval '1 hour';

  insert into waitlist_attempts (ip) values (attempt_ip)
  on conflict (ip) do update set attempts = waitlist_attempts.attempts + 1;

  select attempts into current_attempts from waitlist_attempts where ip = attempt_ip;
  return current_attempts <= 5;
end;
$$;

-- ============ 0025_ai_visibility.sql ============
-- 0025: AI visibility (GEO) - for a tracked query, does an AI answer exist,
-- and is this project's domain cited in it? Two writers share the table:
--   - the daily-ranks cron parses Google's AI Overview out of the same SERP
--     pull that checks rankings (engine 'google_ai_overview'), so Google AI
--     data costs nothing beyond the rank check the project already pays for;
--   - the agent's geo-scan workflow samples answer engines on the user's own
--     subscription and writes results via record_ai_citations (engine
--     'claude' today; 'chatgpt' / 'perplexity' / 'gemini' reserved).
-- Append-only snapshots (like rank_checks) so the dashboard can draw a trend.
create table if not exists ai_snapshots (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null default '00000000-0000-4000-8000-000000000001'
    references projects(id) on delete cascade,
  engine text not null,
  query text not null,
  has_ai_answer boolean not null default false,
  cited boolean not null default false,
  cited_url text,
  -- Verbatim answer snippet: the dashboard shows the actual AI text behind
  -- the number, which is what makes the metric feel real.
  answer_excerpt text,
  -- Every source the answer cited: [{domain, url, title}]. Powers the
  -- "cited instead of you" gap list.
  citations jsonb not null default '[]'::jsonb,
  checked_at timestamptz not null default now()
);

create index if not exists ai_snapshots_project_idx
  on ai_snapshots (project_id, engine, checked_at desc);

-- Same posture as every other table: RLS on, zero policies - service-role only.
alter table ai_snapshots enable row level security;

-- ============ 0026_instance_settings.sql ============
-- First-boot setup wizard (the /setup claim screen). One row max: the
-- instance's dashboard password (scrypt hash) and its generated cron secret.
-- Classic installs that set DASHBOARD_PASSWORD / CRON_SECRET env never write
-- here - env always wins at read time, so applying this to an existing
-- deployment changes nothing.
--
-- No project_id on purpose: this is the door to the whole instance, not
-- tenant state. The `id boolean primary key check (id)` trick caps the table
-- at a single row and makes the claim race safe - the second claimer hits a
-- primary-key conflict instead of silently overwriting the first.
create table if not exists instance_settings (
  id boolean primary key default true check (id),
  dashboard_password_hash text not null,
  cron_secret text not null,
  claimed_at timestamptz not null default now()
);

alter table instance_settings enable row level security;

-- ============ 0027_reliability.sql ============
-- Reliability package (2026-07-20 audit): make the first-boot claim carry
-- everything a self-hosted instance needs so nothing depends on undocumented
-- env vars, and give stuck builds a recoverable timestamp.
--
-- instance_settings.app_url: the instance's own public URL, captured from the
-- claim request. getPipelinePack() bakes it into every connected repo's
-- workflows; before this column, self-hosted deploys silently fell back to
-- the cloud domain and shipped pipelines that phoned the wrong backend.
-- instance_settings.enc_key: auto-generated secrets-encryption key, so the
-- onboarding "connect DataForSEO/SerpApi" path works with zero manual env
-- setup (DATAFORSEO_ENC_KEY env still wins when set; existing encrypted rows
-- keep decrypting with whichever key wrote them).
-- suggestions.started_at: stamped when a build marks a suggestion
-- in_progress; the hourly recovery sweep reverts rows stuck past the
-- workflow's own 45-minute timeout back to approved so a crashed build can
-- never strand the queue.

alter table instance_settings add column if not exists app_url text;
alter table instance_settings add column if not exists enc_key text;

alter table suggestions add column if not exists started_at timestamptz;

-- ============ 0028_auto_approve_tools.sql ============
-- 0028: separate auto-approval toggle for TOOL ideas.
--
-- auto_approve (0011) now means guides only. Tools were "approve-idea-first"
-- by instruction-layer fiat with no flag behind it; this column makes that a
-- real toggle. Default true so auto-mode projects go hands-off on tools too
-- (the auto preset = everything on); the semi preset sets it false. Enforcement
-- stays with the MCP's update_suggestion pending-coercion gate - agent tool
-- approvals land pending when this is off. Auto-approved tools do NOT fire the
-- instant build dispatch (owner approvals do); they wait for the weekly
-- tool-builder sweep, keeping the one-tool-a-week cadence.

alter table projects
  add column if not exists auto_approve_tools boolean not null default true;

-- ============ 0029_gsc_service_account_in_db.sql ============
-- 0029: GSC service-account JSON stored in the DB, encrypted (enc:v1:...),
-- so self-hosters connect Search Console entirely from the onboarding wizard
-- - paste the key file, verified on the spot - instead of editing .env and
-- restarting. The env var GSC_SERVICE_ACCOUNT_JSON still wins when set
-- (classic installs, Vercel deployments); the DB copy is the fallback.
-- Single-row instance_settings, same posture as 0026/0027.

alter table instance_settings add column if not exists gsc_service_account_json text;

-- ============ 0030_wizard_owns_setup.sql ============
-- 0030: the wizard owns the whole setup ("suffer once, then it's done").
--
-- gh_merge_token: the GitHub token behind one-tap merge, stored encrypted
-- (enc:v1:...) so the wizard connects it in-browser like the GSC key (0029)
-- - no .env edit, no restart. Env GH_MERGE_TOKEN still wins when set.
--
-- onboarding_screen: where the wizard last stood for a project, so closing
-- the tab (or a stuck terminal) resumes the wizard at the same screen
-- instead of restarting at step 1. Values are the wizard's screen ids.

alter table instance_settings add column if not exists gh_merge_token text;
alter table projects add column if not exists onboarding_screen text;

-- ============ 0031_cloud_users.sql ============
-- 0031: cloud accounts foundation. Adds project ownership (which Supabase
-- Auth user a project belongs to - null on self-host installs, where there
-- are no users) and the subscriptions table billing will fill in. Additive
-- and zero-downtime like every migration: self-host deployments can apply it
-- harmlessly; nothing reads the new column unless CLOUD_MODE is on.

alter table projects
  add column if not exists owner_user_id uuid references auth.users(id) on delete set null;

create index if not exists projects_owner_user_id_idx on projects (owner_user_id);

-- One row per user, upserted by billing webhooks. Tier limits are stored
-- denormalized (sites_limit/keywords_limit) so enforcement never needs the
-- provider's API on the hot path.
create table if not exists subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'polar',
  provider_customer_id text,
  provider_subscription_id text,
  tier text not null default 'starter',
  status text not null default 'inactive',
  sites_limit integer not null default 1,
  keywords_limit integer not null default 100,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists subscriptions_user_id_idx on subscriptions (user_id);

-- Same posture as every operational table: RLS on, zero policies - only the
-- service-role key (server code) touches it.
alter table subscriptions enable row level security;

